[2025-01-30T18:50:28.053+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T18:50:28.073+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: verifier_repertoire_dag.verifier_et_log_task2 scheduled__2025-01-29T12:00:00+00:00 [queued]>
[2025-01-30T18:50:28.083+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: verifier_repertoire_dag.verifier_et_log_task2 scheduled__2025-01-29T12:00:00+00:00 [queued]>
[2025-01-30T18:50:28.084+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-30T18:50:28.101+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): verifier_et_log_task2> on 2025-01-29 12:00:00+00:00
[2025-01-30T18:50:28.112+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=15435) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-30T18:50:28.114+0000] {standard_task_runner.py:72} INFO - Started process 15437 to run task
[2025-01-30T18:50:28.114+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'verifier_repertoire_dag', 'verifier_et_log_task2', 'scheduled__2025-01-29T12:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/mydag_check_directory.py', '--cfg-path', '/tmp/tmppx7gnfzx']
[2025-01-30T18:50:28.115+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask verifier_et_log_task2
[2025-01-30T18:50:28.183+0000] {task_command.py:467} INFO - Running <TaskInstance: verifier_repertoire_dag.verifier_et_log_task2 scheduled__2025-01-29T12:00:00+00:00 [running]> on host f85a165ecee3
[2025-01-30T18:50:28.521+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='verifier_repertoire_dag' AIRFLOW_CTX_TASK_ID='verifier_et_log_task2' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-29T12:00:00+00:00'
[2025-01-30T18:50:28.522+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T18:50:28.523+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T18:50:28.524+0000] {logging_mixin.py:190} INFO - Current task name:verifier_et_log_task2 state:running start_date:2025-01-30 18:50:28.074369+00:00
[2025-01-30T18:50:28.524+0000] {logging_mixin.py:190} INFO - Dag name:verifier_repertoire_dag and current dag run status:running
[2025-01-30T18:50:28.525+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T18:50:28.525+0000] {logging_mixin.py:190} INFO - Le répertoire existe : /opt/***/dags
[2025-01-30T18:50:28.527+0000] {logging_mixin.py:190} INFO - Contenu du répertoire :  ['mydag_check_directory.py', 'my_directory_and_file_checker.py', 'my_first_dag.py', 'read_import_excel_file_database_mysql.txt', 'shares', '__pycache__']
[2025-01-30T18:50:28.528+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-30T18:50:28.539+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T18:50:28.540+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=verifier_repertoire_dag, task_id=verifier_et_log_task2, run_id=scheduled__2025-01-29T12:00:00+00:00, execution_date=20250129T120000, start_date=20250130T185028, end_date=20250130T185028
[2025-01-30T18:50:28.550+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T18:50:28.551+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T18:50:28.551+0000] {logging_mixin.py:190} INFO - Dag name:verifier_repertoire_dag queued_at:2025-01-30 18:49:17.622473+00:00
[2025-01-30T18:50:28.552+0000] {logging_mixin.py:190} INFO - Task hostname:f85a165ecee3 operator:PythonOperator
[2025-01-30T18:50:28.583+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T18:50:28.600+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T18:50:28.602+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
