[2025-02-06T16:52:02.311+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T16:52:02.340+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: directory_and_file_verification_dag.verify_file_reliability manual__2025-02-06T16:51:53.767171+00:00 [queued]>
[2025-02-06T16:52:02.352+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: directory_and_file_verification_dag.verify_file_reliability manual__2025-02-06T16:51:53.767171+00:00 [queued]>
[2025-02-06T16:52:02.353+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-06T16:52:02.367+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): verify_file_reliability> on 2025-02-06 16:51:53.767171+00:00
[2025-02-06T16:52:02.373+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5870) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-06T16:52:02.375+0000] {standard_task_runner.py:72} INFO - Started process 5872 to run task
[2025-02-06T16:52:02.376+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'directory_and_file_verification_dag', 'verify_file_reliability', 'manual__2025-02-06T16:51:53.767171+00:00', '--job-id', '655', '--raw', '--subdir', 'DAGS_FOLDER/my_directory_and_file_checker.py', '--cfg-path', '/tmp/tmps3794740']
[2025-02-06T16:52:02.377+0000] {standard_task_runner.py:105} INFO - Job 655: Subtask verify_file_reliability
[2025-02-06T16:52:02.419+0000] {task_command.py:467} INFO - Running <TaskInstance: directory_and_file_verification_dag.verify_file_reliability manual__2025-02-06T16:51:53.767171+00:00 [running]> on host 003b7fbea265
[2025-02-06T16:52:02.712+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='directory_and_file_verification_dag' AIRFLOW_CTX_TASK_ID='verify_file_reliability' AIRFLOW_CTX_EXECUTION_DATE='2025-02-06T16:51:53.767171+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-06T16:51:53.767171+00:00'
[2025-02-06T16:52:02.713+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-06T16:52:02.713+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-06T16:52:02.714+0000] {logging_mixin.py:190} INFO - Current task name:verify_file_reliability state:running start_date:2025-02-06 16:52:02.341270+00:00
[2025-02-06T16:52:02.714+0000] {logging_mixin.py:190} INFO - Dag name:directory_and_file_verification_dag and current dag run status:running
[2025-02-06T16:52:02.715+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T16:52:02.716+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-06T16:52:02.726+0000] {my_directory_and_file_checker.py:101} ERROR - ‚ùå Erreur d'encodage (utf-8) pour √âcritures.csv: 'utf-8' codec can't decode byte 0xb0 in position 1: invalid start byte
[2025-02-06T16:52:02.726+0000] {logging_mixin.py:190} INFO - TRRERERRE <class 'NoneType'>
[2025-02-06T16:52:02.727+0000] {logging_mixin.py:190} INFO - ‚ùå Erreur : L'entr√©e doit √™tre un DataFrame pandas.
[2025-02-06T16:52:02.727+0000] {logging_mixin.py:190} INFO - azazazaz None
[2025-02-06T16:52:02.742+0000] {logging_mixin.py:190} INFO - 
üìÇ Contenu du fichier (ISO-8859-1): √âcritures.csv
[2025-02-06T16:52:02.750+0000] {logging_mixin.py:190} INFO -   Date comptabilisation       N¬∞ lot Type √©criture
0            31/12/2024  A-BNDK 2304    Production
1            31/12/2024  B-BNDK 2304    Production
2            31/12/2024  C-BNDK 2304    Production
3            31/12/2024  D-BNDK 2304    Production
4            31/12/2024  E-BNDK 2304    Production
[2025-02-06T16:52:02.751+0000] {logging_mixin.py:190} INFO - /opt/***/files/√âcritures.csv √âcritures.csv  non trait√© Boris None
[2025-02-06T16:52:02.751+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-06T16:52:02.752+0000] {branch.py:38} INFO - Branch into None
[2025-02-06T16:52:02.752+0000] {skipmixin.py:230} INFO - Following branch ()
[2025-02-06T16:52:02.763+0000] {skipmixin.py:278} INFO - Skipping tasks [('end', -1)]
[2025-02-06T16:52:02.784+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T16:52:02.785+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=directory_and_file_verification_dag, task_id=verify_file_reliability, run_id=manual__2025-02-06T16:51:53.767171+00:00, execution_date=20250206T165153, start_date=20250206T165202, end_date=20250206T165202
[2025-02-06T16:52:02.794+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-06T16:52:02.794+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-06T16:52:02.795+0000] {logging_mixin.py:190} INFO - Dag name:directory_and_file_verification_dag queued_at:2025-02-06 16:51:53.780890+00:00
[2025-02-06T16:52:02.795+0000] {logging_mixin.py:190} INFO - Task hostname:003b7fbea265 operator:BranchPythonOperator
[2025-02-06T16:52:02.832+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-06T16:52:02.847+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-06T16:52:02.850+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
