[2025-02-06T16:03:09.086+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T16:03:09.226+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: directory_and_file_verification_dag.verify_file_reliability manual__2025-02-06T16:03:00.327668+00:00 [queued]>
[2025-02-06T16:03:09.235+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: directory_and_file_verification_dag.verify_file_reliability manual__2025-02-06T16:03:00.327668+00:00 [queued]>
[2025-02-06T16:03:09.235+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-06T16:03:09.248+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): verify_file_reliability> on 2025-02-06 16:03:00.327668+00:00
[2025-02-06T16:03:09.254+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5035) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-06T16:03:09.256+0000] {standard_task_runner.py:72} INFO - Started process 5037 to run task
[2025-02-06T16:03:09.256+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'directory_and_file_verification_dag', 'verify_file_reliability', 'manual__2025-02-06T16:03:00.327668+00:00', '--job-id', '601', '--raw', '--subdir', 'DAGS_FOLDER/my_directory_and_file_checker.py', '--cfg-path', '/tmp/tmph92yqhco']
[2025-02-06T16:03:09.257+0000] {standard_task_runner.py:105} INFO - Job 601: Subtask verify_file_reliability
[2025-02-06T16:03:09.299+0000] {task_command.py:467} INFO - Running <TaskInstance: directory_and_file_verification_dag.verify_file_reliability manual__2025-02-06T16:03:00.327668+00:00 [running]> on host 003b7fbea265
[2025-02-06T16:03:09.368+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='directory_and_file_verification_dag' AIRFLOW_CTX_TASK_ID='verify_file_reliability' AIRFLOW_CTX_EXECUTION_DATE='2025-02-06T16:03:00.327668+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-06T16:03:00.327668+00:00'
[2025-02-06T16:03:09.370+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-06T16:03:09.370+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-06T16:03:09.371+0000] {logging_mixin.py:190} INFO - Current task name:verify_file_reliability state:running start_date:2025-02-06 16:03:09.226803+00:00
[2025-02-06T16:03:09.372+0000] {logging_mixin.py:190} INFO - Dag name:directory_and_file_verification_dag and current dag run status:running
[2025-02-06T16:03:09.372+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T16:03:09.373+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-06T16:03:09.383+0000] {my_directory_and_file_checker.py:98} ERROR - ‚ùå Erreur d'encodage (utf-8) pour √âcritures.csv: 'utf-8' codec can't decode byte 0xb0 in position 1: invalid start byte
[2025-02-06T16:03:09.439+0000] {logging_mixin.py:190} INFO - 
üìÇ Contenu du fichier (ISO-8859-1): √âcritures.csv
[2025-02-06T16:03:09.475+0000] {logging_mixin.py:190} INFO -   Date comptabilisation       N¬∞ lot  ... KOR par R√©ception KOR INPUT
0            31/12/2024  A-BNDK 2304  ...             0,000     0,000
1            31/12/2024  B-BNDK 2304  ...             0,000     0,000
2            31/12/2024  C-BNDK 2304  ...             0,000     0,000
3            31/12/2024  D-BNDK 2304  ...             0,000     0,000
4            31/12/2024  E-BNDK 2304  ...             0,000     0,000

[5 rows x 27 columns]
[2025-02-06T16:03:09.478+0000] {logging_mixin.py:190} INFO - ‚ùå Erreur de fiabilit√© : Colonnes manquantes: Date comptabilisation, N¬∞ lot
[2025-02-06T16:03:09.482+0000] {logging_mixin.py:190} INFO - Merde
[2025-02-06T16:03:09.483+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-06T16:03:09.484+0000] {branch.py:38} INFO - Branch into None
[2025-02-06T16:03:09.485+0000] {skipmixin.py:230} INFO - Following branch ()
[2025-02-06T16:03:09.495+0000] {skipmixin.py:278} INFO - Skipping tasks [('end', -1)]
[2025-02-06T16:03:09.518+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T16:03:09.518+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=directory_and_file_verification_dag, task_id=verify_file_reliability, run_id=manual__2025-02-06T16:03:00.327668+00:00, execution_date=20250206T160300, start_date=20250206T160309, end_date=20250206T160309
[2025-02-06T16:03:09.529+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-06T16:03:09.530+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-06T16:03:09.531+0000] {logging_mixin.py:190} INFO - Dag name:directory_and_file_verification_dag queued_at:2025-02-06 16:03:00.338730+00:00
[2025-02-06T16:03:09.531+0000] {logging_mixin.py:190} INFO - Task hostname:003b7fbea265 operator:BranchPythonOperator
[2025-02-06T16:03:09.552+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-06T16:03:09.567+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-06T16:03:09.571+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
